### PR TITLE
Subscribers list bug fix

### PR DESCRIPTION
**Pull request by him3010**

### CODE REVIEW

**Comment by amanwriter** [comment]
Wasn't this a feature, rather than a bug? We wanted to persist messages in Redis queue in case the subscribed service was down, which will begin processing it when it comes up.

**Comment by him3010** [comment]
@amanwriter  yup forget that case thanks by the way.. One quick question why the registered services list would not get updated when the service was not available at all. Meaning a new service comes up and the after some testing it is removed from the system. I can still see the service in registered services

**Comment by amanwriter** [comment]
The self._registered_services dict will always contain the service_name and version, however, it wouldn't contain any instances in case all instances get de-registered, but the service_name and version would always be there, for the xsubscribe message persistence use-case mentioned.

**Comment by him3010** [comment]
@amanwriter  we should expose a endpoint in registry where we can tell registry that this service is not available in our system so remove all the dependencies. That would be the best case in the current implementation

**Comment by him3010** [comment]
Specialy in case of XSubscription otherwise unneccesary events will be adding into the queue and with the time the size of queue(redis) can increase and may result in outage.

**Comment by amanwriter** [comment]
Yes, you can modify existing blacklist API for the same, to remove service permanently, and pop the key from self._registered_services

**Pull request closed without merging**
